### ISSUE TITLE
[BUG] SDLink prevents Fabric server from properly stopping.

### ISSUE THREAD

**Issue by ghost** [hypherionmc/sdlink#1]
Fabric Version: 1.12.9
Fabric API Version: 0.44.0
SDLink Version:1.0

When running the stop command, the server hangs without any appear errors or messages in either the console or logs. Forcing you to Kill/Force Stop the server.

After testing, I narrowed it down to SDLink and confirmed it happens without any other mods installed. It has occurred on both a locally hosted dev server and the main server hosted through BisectHosting.

Reproduction: Setup a Fabric server with SDLink of the above mentioned versions. Start the server, run the stop command. If running locally, the GUI will disappear but if you check Task Manager the Java process is still running.

**Comment by hypherionmc** [comment]
I can indeed confirm this bug. I noticed it in my dev environment, but didn't think much of it, cause I thought it was just gradle acting up.

**Comment by hypherionmc** [comment]
Bug has been fixed in 1.1
