### ISSUE TITLE
Can’t mention people from Minecraft

### ISSUE THREAD

**Issue by FuzzyL16** [hypherionmc/sdlink#100]
I have the setting on for mentions but it doesn’t work I’m not sure if I’m understanding it correctly or if there is a specific syntax I have to do I have I have tried @DiscordUser and @MinecraftUser both didn’t work

Again not sure if this is a bug or if I’m doing it incorrectly

**Comment by hypherionmc** [comment]
It's been a while, but it seems like one of our testers actually verified this. It seems to be a lack of proper documentation on our part.

So for client side mentions to work, you need both craterlib and sdlink installed, and the "allowMentions" setting in the config on the server set to true.

Then, in game, to mention someone, you need to type [@ or [# to trigger the suggestions for mentions. [@ works for both users and roles, while [# works for channels.

**Comment by FuzzyL16** [comment]
Thank You! I got it Working!
👍

**Comment by hypherionmc** [comment]
Finally added this to the documentation :)

https://sdlink.fdd-docs.com/features/client-mentions/
