### ISSUE TITLE
Mod does not send messages from Discord to Minecraft

### ISSUE THREAD

**Issue by BuildCraft001** [hypherionmc/sdlink#105]
I have now set up the mod on my server, and as described in the wiki, also the bot on my Discord server.
The messages when the server starts/stops, players join/leave or die and also chat messages from Minecraft are transmitted on Discord to the respective channels set for this purpose. 
The only problem is that messages from Discord are not displayed on the Minecraft server.

I am using version 2.2.4 of the mod on Forge 45.2.0 (Minecraft 1.19.4)

This is my config file (without private Discord data):

#General Mod Config
[general]
	#Should the bot be enabled or not
	enabled = true
	#Should debug logging be enabled? WARNING: THIS CAN SPAM YOUR LOG!
	debugging = false
	#Should the bot be allowed to whitelist/un-whitelist players. Whitelisting needs to be enabled on your server as well
	whitelisting = false
	#Should the bot be allowed to whitelist/un-whitelist players in OFFLINE mode. Whitelisting needs to be enabled on your server as well
	offlinewhitelist = false
	#Automatically link Minecraft and Discord Accounts when a user is whitelisted
	linkedWhitelist = false
	#Should only admins be allowed to whitelist players
	onlyAdminsWhitelist = false
	#If a role ID (or name) is defined here, it will be assigned to players when they are whitelisted
	autoWhitelistRole = ""
	#Modify user nickname when their accounts are linked
	modifyNickname = false
	#If a role ID (or name) is defined here, it will be assigned to players when their MC and Discord accounts are linked
	linkedRole = ""
	#Should the /discord command be enabled in game
	inviteCommandEnabled = false
	#Discord Invite Link used by the in-game invite command
	inviteLink = ""
	#Internal version control. DO NOT TOUCH!
	configVersion = 25

#Config specific to the discord bot
[botConfig]
	#The Token of the Bot to use. KEEP THIS PRIVATE. See https://readme.firstdarkdev.xyz/simple-discord-link/initial-setup/ to find this
	botToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	#How quickly the bot status should update
	activityUpdateInterval = 30
	#If a role ID (or name) is defined here, only members with this role can use Staff Functions. Otherwise, it defaults back to admin/kick perms
	staffRole = ""
	#Should the bot use / commands. NOTE: THIS MAY TAKE UP TO 24 HOURS TO SHOW UP IN YOUR DISCORD
	slashCommands = true
	#The prefix to use for bot commands. Example: ~players. THIS HAS NO EFFECT WHEN USING SLASH COMMANDS
	# - WARNING: TEXT COMMANDS HAVE BEEN DEPRECATED, USE SLASH COMMANDS INSTEAD!!
	botPrefix = "~"
	#Do not add Playing. A status to display on the bot. You can use %players% and %maxplayers% to show the number of players on the server
	botStatus = "CS Skywars - Reimagined"
	#The type of the status displayed on the bot. Valid entries are: PLAYING, STREAMING, WATCHING, LISTENING
	botStatusType = "PLAYING"
	#The URL that will be used when the "botStatusType" is set to "STREAMING", required to display as "streaming".
	botStatusStreamingURL = "https://twitch.tv/twitch"
	#Should the bot update the topic of your chat channel automatically
	doTopicUpdates = true
	#A topic for the Chat Relay channel. You can use %player%, %maxplayers%, %uptime% or just leave it empty.
	channelTopic = "Playing CS Skywars - Reimagined with %players%/%maxplayers% people | Uptime: %uptime%"

#Config relating to the discord channels to use with the mod
[channels]
	#The ID of the channel to post in and relay messages from. This is still needed, even in webhook mode
	chatChannelID = 1205904061598015600
	#If this ID is set, event messages will be posted in this channel instead of the chat channel
	eventsChannelID = 0
	#If this ID is set, console messages sent after the bot started will be relayed here, and you can execute minecraft commands here
	consoleChannelID = 0

#Webhook Config
[webhooks]
	#Should webhook messages be used
	enabled = true
	#The URL of the channel webhook to use for Chat Messages
	chatWebhook = "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	#The URL of the channel webhook to use for Server Messages
	eventsWebhook = "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	#The URL of the channel webhook to use for Console Messages
	consoleWebhook = "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
	#A DIRECT link to an image to use as the avatar for server messages. Also used for embeds
	serverAvatar = ""
	#The name to display for Server messages when using Webhooks
	serverName = "Skywars"

#Chat Config
[chat]
	#The type of image to use as the player icon in messages. Valid entries are: AVATAR, HEAD, BODY, COMBO
	playerAvatarType = "HEAD"
	#Prefix to add to Minecraft when a message is relayed from Discord. Supports MC formatting. Use %user% for the Discord Username
	mcPrefix = "§e[Discord]§r %user%: "
	#Should messages from bots be relayed
	ignoreBots = true
	#Should SERVER STARTING messages be shown
	serverStarting = true
	#Should SERVER STARTED messages be shown
	serverStarted = true
	#Should SERVER STOPPING messages be shown
	serverStopping = true
	#Should SERVER STOPPED messages be shown
	serverStopped = true
	#Should the chat be relayed
	playerMessages = true
	#Should Join and Leave messages be posted
	joinAndLeaveMessages = true
	#Should Advancement messages be posted
	advancementMessages = false
	#Should Death Announcements be posted
	deathMessages = false
	#Should Messages from the /say command be posted
	sendSayCommand = true
	#Should commands be posted to discord
	broadcastCommands = false
	#Commands that should not be broadcasted to discord
	ignoredCommands = ["particle", "login"]

#Change the contents of certain event messages
[messages]
	#Convert Discord to MC, and MC to Discord Formatting
	formatting = true
	#Should console messages be sent to the Console Channel
	sendConsoleMessages = true
	#Server Starting Message
	serverStarting = "*Server is starting*"
	#Server Started Message
	serverStarted = "*Server has started*"
	#Server Stopping Message
	serverStopping = "*Server is stopping*"
	#Server Stopped Message
	serverStopped = "*Server has stopped*"
	#Player Joined Message. Use %player% to display the player name
	playerJoined = "*%player% has joined*"
	#Player Left Message. Use %player% to display the player name
	playerLeft = "*%player% has left*"
	#Achievement Messages. Available variables: %player%, %title%, %description%
	achievements = "*%player% has made the advancement [%title%]: %description%*"
	#Chat Messages. Available variables: %player%, %message%
	chat = "%message%"
	#Command Messages. Available variables: %player%, %command%
	commands = "%player% **executed command: %command%**"
	#Should messages sent with TellRaw be sent to discord as a chat? (Experimental)
	relayTellRaw = true
	#Should the entire command executed be relayed to discord, or only the name of the command
	relayFullCommands = false
	#The message to show when someone uses /discord command. You can use %inviteurl%
	inviteMessage = "Hey, check out our discord server here -> %inviteurl%"

#Change in which channel messages appear
[messageDestinations]

	#Control where CHAT messages are delivered
	[messageDestinations.chat]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where START/STOP messages are delivered
	[messageDestinations.startStop]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where JOIN/LEAVE messages are delivered
	[messageDestinations.joinLeave]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where ADVANCEMENT messages are delivered
	[messageDestinations.advancements]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where DEATH messages are delivered
	[messageDestinations.death]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

	#Control where COMMAND messages are delivered
	[messageDestinations.commands]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false

#Enable or Disable certain bot commands
[botCommands]
	#Allow members to link their MC and Discord accounts
	accountLinking = true
	#Enable/Disable the Player List command
	allowPlayerList = false
	#Enable/Disable the Server Status command
	allowServerStatus = false

#Execute Minecraft commands in Discord
[linkedCommands]
	#Should linked commands be enabled
	enabled = false
	#Commands to be linked
	commands = []

I think I found the reason for the problem myself, because the file editor shows me the following for the Discord Channel ID:
![Dateien _ exaroton _ Hochwertige auf Abruf verfügbare Gameserver – Mozilla Firefox 10 02 2024 19_40_05](https://github.com/hypherionmc/sdlink/assets/127152560/d5492c59-00f9-4028-9bbf-a51ef76d7767)

If I deactivate the webhooks, no more messages from the server are received on Discord.
Logically, the reason for this should be that the server cannot read this channel ID because it is not a valid integer. However, I wonder why it works on other servers and not on mine.

If that helps: The server is hosted by Exaroton (exaroton.com). As far as I know, they use Linux as the operating system for their servers.

**Comment by hypherionmc** [comment]
Version 2.2.4 is a broken version on a lot of servers for some reason.

You will either need to downgrade to an older version, or upgrade to the new V3 beta version

**Comment by BuildCraft001** [comment]
I just tried it, the exact same thing happens with v2.2.2, v2.2.1, v3.0.0 and v3.0.1 as well

**Comment by hypherionmc** [comment]
> read this channel ID because it is not a valid integer.

The editor is right. Discord channel ID's are not integers. They are LONG. Sadly, most GUI editors are not smart enough to know this.

The fact that messages do not come through without webhooks, do indeed indicate it's an issue with the channel itself.

In your logs there should be a massive wall of text printed from SDLink if there is a permission issue with the channels you are using, which is normally the case for Discord -> MC messages not being relayed

**Comment by BuildCraft001** [comment]
I have checked several times that the bot has the necessary authorisations for the channel, and it does. The log does not mention any problems with permissions.

But I saw something interesting in the console when I started the server:

[JDA MainWS-WriteThread] ERROR WebSocketClient - WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode[DISALLOWED_INTENTS](code=4014, meaning=Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES, MESSAGE_CONTENT, or GUILD_MEMBERS.)

I don't know exactly what it means, but maybe it has something to do with my problem

**Comment by hypherionmc** [comment]
Ah, there we go. 

You missed a step when creating your discord bot.

For V3: [Gateway Intents](https://sdlinkbeta.fdd-docs.com/installation/bot-creation/#privileged-gateway-intents)
For V2: [Gateway Intents](https://sdlink.fdd-docs.com/initial-setup/#part-3---bot-permissions-and-inviting-the-bot)

Both are pretty much the same. The docs for V3 is just more detailed

**Comment by BuildCraft001** [comment]
Oh god, I just missed this one switch... I feel so stupid right now xD
But anyways, thanks for your help!
And keep up your work! This mod is brilliant
