### ISSUE TITLE
[Feature] Support Threads/Forum Posts (At least in webhook mode)

### ISSUE THREAD

**Issue by laundmo** [hypherionmc/sdlink#109]
As it stands, the bot cannot send messages to forum threads. I suspect partly because it parses webhook addresses instead of using them as-is.

A webhook can send to a thread or forum post using the `?thread_id=111111111` query parameter just fine. Using a thread webhook would be a nice workaround for being able to set the bot up for threads, but it seems not to send these webhooks successfully.

I understand that wanting to proxy a thread's chat is a rare use case, if it isn't worth it so be it.

**Comment by hypherionmc** [comment]
So supporting this would depend on the webhook library we make use of, [discord-webhooks](https://github.com/MinnDevelopment/discord-webhooks).

Last time I checked, they didn't support this yet. The webhook url is passed from the config directly to this library, and it handles the rest.

So if they support it, then yes we can too. If they don't, then they'd need to add support for it.


Just curious, what's the use case for this?

**Comment by laundmo** [comment]
I run a semi-official minecraft server for a discord community, the main admin of which didn't want to add a full channel for the server so theres a forun thread instead

**Comment by hypherionmc** [comment]
I see. That makes sense.

So basically you'd need us to support using a single thread or forum post to relay chats to and from?

**Comment by laundmo** [comment]
yup, but i fully understand if its too niche

**Comment by hypherionmc** [comment]
Found a way to make webhooks work. Will be released after testing.

With this release it will also be possible to use threads for chat and other relays

![image](https://github.com/hypherionmc/sdlink/assets/63595580/0e5d0da4-d37e-43a6-a3f6-0e28e0687515)

**Comment by hypherionmc** [comment]
Implemented in 3.1.0

**Comment by mrbeezwax** [comment]
Hey, thanks for adding this! Would it be worth updating the Documentation to also require the "Send Messages in Threads" bot permission? For me, I wasn't able to get it to send messages in the thread until I allowed this for the bot.

![image](https://github.com/hypherionmc/sdlink/assets/2925785/31b91048-1dd9-418f-a31e-1a6546f960f2)

![image](https://github.com/hypherionmc/sdlink/assets/2925785/2aa2cda5-01d3-40ec-9949-83257ff74375)
