### ISSUE TITLE
[Feature] Customize the Avatar Image for Webhooks

### ISSUE THREAD

**Issue by AllOutJay** [hypherionmc/sdlink#11]
[Feature] I think it would be nice to have the ability to customize the avatar image for webhook messages to a different site or having more options.

**Comment by hypherionmc** [comment]
By customize, do you mean the images used for Chat webhooks, which is currently the player head?

**Comment by AllOutJay** [comment]
Yep! I think the image generated from https://mc-heads.net/avatar/alloutjay.png personally looks better or I know some mods have the ability to do busts/the upper half of the body as the images used in the chat webhooks where the player head is.

**Comment by hypherionmc** [comment]
Hmm. I'll check it out. As for mc-heads.net, I just gave it a quick look and the site takes very long to load compared to crafatar, which concerns me a bit, but it's still worth considering

**Comment by AllOutJay** [comment]
There is also https://minecraftskinstealer.com/avatars/skin/alloutjay and I am sure other sites that do the same thing

**Comment by AllOutJay** [comment]
@hypherionmc I think the positioning of some of the options needs to be modified as it doesn't look right or seems off.

**Comment by hypherionmc** [comment]
Do you have pictures?

I didn't send any additional info to the api aside from the UUID, so it's all their default settings

**Comment by AllOutJay** [comment]
Body seems to focus a little too low. Combo, I'm not sure what that was suppose to be a combination of, but it just looks like the avatar and a full render thrown on the right side. I have not tried the Head option just yet.

![image](https://user-images.githubusercontent.com/80604256/183090089-724c9276-0359-4521-a887-3527b4b9b2ac.png)
