### ISSUE TITLE
[1.20.4 Fabric Server] Crashing on Startup

### ISSUE THREAD

**Issue by Jh16** [hypherionmc/sdlink#110]
Hello, I recently updated to 1.20.4 from 1.20.1 and went through the appropriate V2 to V3 migration, but something isn't quite working right.
Until then, I'll not have the mod.

Here is a pastebin of the log:
https://pastebin.com/Cqc0aYxU

Any help would be appreciated!
Thanks

Edit:
_Using the 3.0.1 version from Modrinth_

**Comment by hypherionmc** [comment]
> Caused by: shadow.hypherionmc.moonconfig.core.conversion.InvalidValueException: Unexpected element of type class java.lang.Long in collection of objects

I suspect this is something we missed in the migration guide, but channel ids now need to be wrapped in "".

So if the id was 12345657 in V2, it must be "12345657" in v3

**Comment by Jh16** [comment]
Okay, let me check through all that and I will post back!

**Comment by Jh16** [comment]
All of those were in "".

When I updated, I let the mod create an empty config file for me. That way, I could copy and paste what I needed to.
Perhaps it is something that I overlooked. It wouldn't be the comma and space to separate the role ids would it?

Edit:
Put config, minus bot token and discord into pastebin. Maybe you'll see something there that is incorrect.
https://pastebin.com/Gcqz1yks

**Comment by hypherionmc** [comment]
> requiredRoles = [1092609240293707783, 1063297870574399488, 1063294577349492800]
> deniedRoles = [1065533343824887818]

These all need to be in ""

For reference: [SDLink Beta Docs](https://sdlinkbeta.fdd-docs.com/features/whitelisting/#only-allow-access-to-certain-roles)

**Comment by Jh16** [comment]
Oooh, I must have missed that initially *facepalm*

**Comment by Jh16** [comment]
Cheers!
