### ISSUE TITLE
[feature Request] using channel ids/webhooks to customize where to send messages to

### ISSUE THREAD

**Issue by Rockiecraft** [hypherionmc/sdlink#116]
for example, maybe i wanna have a channel specifically where commands get sent to and nothing else.

I think it would be nice to be able to send specific messages to specific channels of their own. 

like further than the 3 preset places we can to send them right now

**Comment by hypherionmc** [comment]
Implemented in 3.2.0

**Comment by Rockiecraft** [comment]
yoo les go. thanks
