### ISSUE TITLE
Old versions of messages are NOT sent via a bot

### ISSUE THREAD

**Issue by RockZe** [hypherionmc/sdlink#119]
In one of the latest updates, the setting and configuration of the mod has changed, now it is in a separate folder, and not as before. I've moved all the old settings, but now I'm faced with a strange problem, namely - previously, all player messages from the server and notifications about start and stop were either on behalf of the players themselves or on behalf of the server. Now it is the BOT that carries ALL notifications. What is the problem? In addition to the visual component, the bot also spams scheduled phrases that are configured for me every 30 minutes via the / say command (that is, the phrase of the server itself). For discord, this is a huge spam, and this has never happened before. 
Is it possible to return messages NOT through a bot, as before?

**Comment by hypherionmc** [comment]
Um okay all this is completely weird, because the new update didn't touch any of the areas that you are mentioning.


Can you show me some screenshots of whats happening?


Wait. It sounds like you updated from a 2.x release to a 3.x release. Is that accurate?

**Comment by RockZe** [comment]
I can't find the old server files, but it seems yes, we switched from the version where configVersion = 17 was, and now to version 25

It looks like this. Above, where in white, there was a response from the "server", and not from the bot itself, but below, the bot itself responds in red, and it pulls everything that is in the chat, even the messages of the server itself
![image](https://github.com/user-attachments/assets/add2a36e-41fd-4c3d-ae8c-548349294afc)

**Comment by hypherionmc** [comment]
Okay yeah something is definitely weird here.

Our current release version, is only on config 17, so version 25 is.... Very weird. Version 25 was the last version of 2.x that we released, so if that is really the case, you downgraded instead of upgrading

Can you show me a copy of the config file please? Just remove any sensitive data from it like your bot token and any webhook urls that appear in plain text

**Comment by RockZe** [comment]
Oh, okay, maybe I'm wrong. Let's put it this way, I know for sure that before the file was called simple-discord-bot and lay in the "config\" folder, while the new file is called simple-discord-link and lies along the path "config\simple-discord-link\"

Moreover, what else did I notice. Previously, the bot did not need to be granted the rights to "write in the channel" and notifications came anyway. Now, in order for the bot to write at least something, it needs to be granted rights.

OK, I'll add a new config below
[simple-discord-link.txt](https://github.com/user-attachments/files/16475531/simple-discord-link.txt)

**Comment by hypherionmc** [comment]
Alright.

So those messages are called webhooks, which you do have configured in the new config, but it's disabled. That's why all the messages is being delivered through the bot.

```toml
[channelsAndWebhooks.webhooks]
	#Prefer Webhook Messages over Standard Bot Messages
	enabled = false
```

The part about the say being spammed, you can also disable that in the config under

```toml
#Should Messages from the /say command be posted
	sendSayCommand = false
```

**Comment by RockZe** [comment]
Oh, it really sounds like a solution to the problem, although I was sure I had set these settings. In any case, I will try to check and let you know!
