### ISSUE TITLE
Vanish mod does not work

### ISSUE THREAD

**Issue by Lunatrixen** [hypherionmc/sdlink#120]
https://modrinth.com/mod/vanishmod

mc: 1.20.1
mod: 3.1.4
loader: Forge
loader version: 47.2.17
crater: 2.0.2

Mod prevents messages to be sent from minecraft to discord.

**Comment by hypherionmc** [comment]
Should be fixed with 3.1.5 and CraterLib 2.0.3 :)

Thanks for reporting
