### ISSUE TITLE
bot keeps spamming that user is "executing command"

### ISSUE THREAD

**Issue by Aiko0508** [hypherionmc/sdlink#121]
![problem](https://github.com/user-attachments/assets/97d88862-cb59-49c4-b08a-28fba00f6b0c)

bot keeps spamming these in my server when someone is online in the game. please help

**Comment by hypherionmc** [comment]
Add the name of the commands that are being spammed into the `ignoredCommands` list, and use the /reloadbot command in minecraft, or restart your server.

So in this case, you want to add `function` and `title` into that list

**Comment by Aiko0508** [comment]
> Add the name of the commands that are being spammed into the `ignoredCommands` list, and use the /reloadbot command in minecraft, or restart your server.
> 
> So in this case, you want to add `function` and `title` into that list

thanks. i think it worked
