### ISSUE TITLE
Chat heads not embedding into Discord despite config

### ISSUE THREAD

**Issue by larrymaple** [hypherionmc/sdlink#124]
Minecraft ver. 1.21.1
Fabric ver. 0.16.5
Mod ver. 3.1.6 (downloaded from [here](https://cdn.modrinth.com/data/Sh0YauEf/versions/mDnw4mrB/SimpleDiscordLink-Universal-3.1.6.jar))

The following config entry has been set:

```
#The type of image to use as the player icon in messages. Valid entries are: AVATAR, HEAD, BODY, COMBO
    playerAvatarType = "HEAD"
```

And yet when a player chats in-game, there is no icon in the correlated discord server showing that player's head. Everything else is working fine. 

![image](https://github.com/user-attachments/assets/4e2075c5-7d46-4f0a-8c3c-7efeba82af09)

Please let me know if further information is required. Thank you.

**Comment by hypherionmc** [comment]
Player heads only work in Webhook mode, and when using embeds.

What you are using here is standard bot messages. Discord does not provide a way to dynamically change the bot icon

**Comment by larrymaple** [comment]
Thank you, I will swap to that mode immediately.
