### ISSUE TITLE
[BUG] The Verified Role doesn´t get assigned when someone does /verify <their code>

### ISSUE THREAD

**Issue by NextRaven10** [hypherionmc/sdlink#125]

**Comment by hypherionmc** [comment]
Check your log for errors. Most common reasons for this not working is:

Incorrect role configured
Bot doesn't have the appropriate permissions
The role hierarchy is incorrect

All of which will be logged

**Comment by NextRaven10** [comment]
the role hierachy was wrong. Thx for the fast answer :)
