### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by VaporeonScripts** [hypherionmc/sdlink#127]
![image](https://github.com/user-attachments/assets/8f3b00d8-ccbb-4ed1-94f6-ddf594c46a5e)

**Comment by VaporeonScripts** [comment]
does it mean i can put the role id so only the person with that role can run commands or what

**Comment by NighthowlerStudios** [comment]
Please read our wiki in the Linked Commands section.  This is a non-issue.
