### ISSUE TITLE
[Feature] Disable embeds for chat messages but not server status messages

### ISSUE THREAD

**Issue by ChristopherHaws** [hypherionmc/sdlink#13]
I would like to be able to have normal chat messages not use embeds but have join/leave messages and server started/stopped messages keep using embeds. From what I can see, there is only the `useEmbeds` option which applies to all messages.

Thanks!

**Comment by hypherionmc** [comment]
Hi. Sorry for the late reply.

I will add this to the next update. I'm currently working through bug reports and feature suggestions, so should be soon

**Comment by hypherionmc** [comment]
Feature has been added in release 1.4.0 which is now live on Curse and Modrinth

**Comment by ChristopherHaws** [comment]
Thanks so much!
