### ISSUE TITLE
[BUG] `%player%` not replaced with linked name in event messages

### ISSUE THREAD

**Issue by thorimur** [hypherionmc/sdlink#131]
On event messages like joining or leaving the server, deaths, and command messages, `%player%` is not replaced with the linked discord nickname when relayed to discord, and instead displays as just the Minecraft username. However, `%player%` *is* successfully replaced with the linked discord name within chat messages (i.e. within Minecraft chat messages that are relayed to discord).

I'm observing this on a minimally-modded 1.21.3 Fabric server and a maximally-modded 1.21.1 Neoforge server, on an M-series Mac within a docker container (which I hope is not relevant, given that the replacement succeeds for chat messages).

Thanks for maintaining this mod! :)

(Also, I hope I've correctly identified this as a bug, and that it's not intended behavior. If it is intentional, I'd request a feature to use the linked discord name in event messages.)

**Comment by hypherionmc** [comment]
Hmmm. This definitely sounds like a bug. It's supposed to use the linked name everywhere when `useLinkedNames` is enabled. 

I guess I just never picked this up because my discord and mc name is the same. Will take a look into this. Thanks for reporting :)

**Comment by hypherionmc** [comment]
I almost completely forgot about this :facepalm: 

I was just about to do a release when this caught my eye. 

So the reason this happens is, those messages are sent as the "server", so the linked account information is never passed to it. I am going to fix this now, because it's supposed to work on those as well

**Comment by hypherionmc** [comment]
Fixed in 3.2.1
