### ISSUE TITLE
what color do i use now? as it gives error

### ISSUE THREAD

**Issue by VaporeonScripts** [hypherionmc/sdlink#132]
![image](https://github.com/user-attachments/assets/f64a212d-ae5b-4cbe-b1ad-b041c8f4914a)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/148309b0-6226-4d63-add5-f25254474cfa)

**Comment by hypherionmc** [comment]
Did you update craterlib when you updated?

**Comment by VaporeonScripts** [comment]
nope, theres no update

**Comment by VaporeonScripts** [comment]
looks like there is but didnt show

**Comment by hypherionmc** [comment]
CraterLib 2.1.2 was released this morning, long before sdlink. Probably just an api glitch

**Comment by VaporeonScripts** [comment]
updated, will that color work now?

**Comment by VaporeonScripts** [comment]
works

**Comment by hypherionmc** [comment]
Yes. It only gave an error cause there was a bug in craterlib, which had a temporary work around in SDLink, but since the bug also affected maintenance mode, it was fixed in the new release.

You can still use the mc formatting, or you can use minimessage formatting (which imo is a bit cooler lol)
