### ISSUE TITLE
[Feature] FabricTailor support

### ISSUE THREAD

**Issue by Azarattum** [hypherionmc/sdlink#19]
[FabricTailor](https://github.com/samolego/FabricTailor) is a server-side mod that allows players dynamically change their skins in-game. It would be great if `sdlink` were able to check whether `FabricTailor` is installed and show player skins in discord accordingly.

**Comment by hypherionmc** [comment]
Hi.

Sorry for only responding now. I'll take a look at it and see how we can add support for them

**Comment by hypherionmc** [comment]
Alright, so turns out there is a way to get the skins provided by the mod, but rendering it as a head/body etc is a whole different story. So this is planned for a future release

**Comment by Azarattum** [comment]
Great to hear that! Thanks for your amazing work!

**Comment by hypherionmc** [comment]
Release 2.0 contains support for FabricTailor. I haven't tested it myself, but following their advise, it should be working

**Comment by Azarattum** [comment]
@hypherionmc thanks! Can confirm that it works flawlessly.
