### ISSUE TITLE
Fabric 1.19.2 latest update 2.0.0 not working

### ISSUE THREAD

**Issue by gamerpotion** [hypherionmc/sdlink#20]
Hi, ive been using SimpleDiscordLink-fabric-1.19.1-1.4.1.jar on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
and its been working perfectly on our official server.

The latest update SimpleDiscordLink-fabric-1.19.1-2.0.0.jar  doesnt seem to register the mod when loading the game or create a new config file.

Looking into the console, there is not information loaded in there either.

**Comment by hypherionmc** [comment]
Hi. Do you have a server log for me? 2.0.0 does require redoing the config, but it's supposed to make a backup of your old one and create a new one

**Comment by gamerpotion** [comment]
Hi, thanks for the reply. I managed to get it to create the new config, however there was an issue where server chat was not working properly and things like spawn commands stopped working in game.
I have reverted back to the old version till can figure it out.

**Comment by gamerpotion** [comment]
Hi, just to update that I managed to get the new version to work and the webhooks are also working now. There seems to be a slight lag in player count shown on the top compared to the player count of the ChatBot
https://discord.gg/a7Xsp5N9py  - you can see it in action if you wish.
