### ISSUE TITLE
[Bug] [MC 1.18] [Mod Version: 2.0.1] Crash when user logs into server 

### ISSUE THREAD

**Issue by benjamin-Keller** [hypherionmc/sdlink#23]
Hi,
Title says it all, Minecraft 1.18.1, Mod version 2.0.1.

Saw another issue about 1.19 was posted, but this is for 1.18.1
Crashlog:
[crash-2022-11-12_18.18.47-server.txt](https://github.com/hypherionmc/sdlink/files/9995643/crash-2022-11-12_18.18.47-server.txt)

**Comment by hypherionmc** [comment]
Hi

Okay that is an interesting one. Can you send me your server log from when this occured? Seems like its lagging out the server when trying to send the join message

**Comment by benjamin-Keller** [comment]
Sure thing, give me a few mins

**Comment by benjamin-Keller** [comment]
[2022-11-12-4.log](https://github.com/hypherionmc/sdlink/files/9995657/2022-11-12-4.log)

**Comment by hypherionmc** [comment]
Okay nothing definitive there to tell me what happened. Does this happen repeatedly?

**Comment by benjamin-Keller** [comment]
both our test server and production server crash when someone joins

**Comment by hypherionmc** [comment]
That's odd.

Are you using webhooks or channels?

And if possible, can you enable the debug option in the sdlink config and try joining again. It should then log all additional errors.

As a last resort, I may ask you to provide me with a copy of the mods on your server so we can test on our side (if it's possible for you to do so)

**Comment by benjamin-Keller** [comment]
I'll turn on the debug option now and test it again.
We aren't using Webhooks no, just two channels on Discord (one for chat and one for logs), and speaking about logs, is there any way to stop execute commands from repeating command block from spamming the log channel?

The modpack we use is Kindom of Eternia from NerdyDragon42 (me), version 1.4.1.

I'll comment again in a bit with a new server log from the test server of ours

**Comment by benjamin-Keller** [comment]
Crash log:
[crash-2022-11-12_19.12.27-server.txt](https://github.com/hypherionmc/sdlink/files/9995737/crash-2022-11-12_19.12.27-server.txt)

Server log:
[2022-11-12-1.log](https://github.com/hypherionmc/sdlink/files/9995739/2022-11-12-1.log)

**Comment by benjamin-Keller** [comment]
Oh, here is my config too, I'll be regenning my token after this, but for now keeping it until this has been troubleshooted
[simple-discord-bot.txt](https://github.com/hypherionmc/sdlink/files/9995747/simple-discord-bot.txt)

**Comment by hypherionmc** [comment]
> stop execute commands from repeating command block from spamming the log channel

That's a very important piece of information right there. That would definitely cause the server lock-up, and a player joining is enough to send it over the edge and crash it.

If your config, find this part under `chat`.

```toml
#Commands that should not be broadcasted to discord
ignoredCommands = ["particle", "login"]
```

Add `"execute"` to that list. So it will become `ignoredCommands = ["particle", "login", "execute"]`.

That should ignore the execute command and stop it from spamming/causing the server crash

**Comment by benjamin-Keller** [comment]
I'll give this a try

**Comment by benjamin-Keller** [comment]
Ok that fixed it and it works well, thanks a ton @hypherionmc

**Comment by hypherionmc** [comment]
You're welcome and thanks for letting me know. It gave me an idea for a future improvement as well

**Comment by benjamin-Keller** [comment]
If I can recommend, no idea how possible it is but taking notes from lucky perms (plugin on PaperMC), maybe we can get a localhost site we can use to edit config? Maybe something like `/discord edit` and it opens a site we can directly edit config, on save it run the reload config command?

**Comment by hypherionmc** [comment]
Not a bad idea at all. Will definitely look into this

**Comment by benjamin-Keller** [comment]
Send me a message if you'd need any help of any kind, I'm a fullstack dev, mainly dotnet, if needed: Nerdy#5660 is my discord
