### ISSUE TITLE
Localization seems to not be working

### ISSUE THREAD

**Issue by ChristopherHaws** [hypherionmc/sdlink#26]
Hey there! It seems like localization doesn't seem to be working for events:
![image](https://user-images.githubusercontent.com/5934505/203432796-af9348b0-b8ee-44e4-ac47-45e0e6839f9e.png)

**Comment by hypherionmc** [comment]
Wow. When the heck did we break that....

Is this on forge or fabric?

**Comment by ChristopherHaws** [comment]
It's on fabric. I am on the latest version. I do have a lot of mods installed. Is it possible it is being broken by another mod?

I just went back in my server logs and apparently it was working at 9pm yesterday. So something recently broke it (be it a mod or config). I havent had a chance to dig into it yet.

![image](https://user-images.githubusercontent.com/5934505/203434633-e3bf7862-b713-4483-9e66-688f8bfdd9bb.png)

**Comment by hypherionmc** [comment]
Thanks for the update. So I looked over our code for the update, and I don't see anything that we changed with regards to advancements, so my best guess here is definitely a mod interference. If we can find the culprit, I can look at adding a fix or workaround for it to push out with the webhooks release

**Comment by hypherionmc** [comment]
I wonder if this is related to #32. The beta build might fix this as well if this issue still occurs

**Comment by hypherionmc** [comment]
Hopefully this was fixed with release 2.1. If this issue still persists, please feel free to reopen
