### ISSUE TITLE
Strip Minecraft formatting from messages

### ISSUE THREAD

**Issue by ChristopherHaws** [hypherionmc/sdlink#27]
It looks like formatting codes do not get stripped from messages before sending to discord. Would it be possible to remove all format codes from the message? Optionally, you could modify the message to support some of the formatting codes (bold, italic, underline) by converting the message to us discords markdown syntax. For now, I would be happy with just stripping everything though if that is too much work. :)

![image](https://user-images.githubusercontent.com/5934505/203636279-859fc383-bb1e-4e0e-9efa-0ed0c9b41502.png)

**Comment by hypherionmc** [comment]
Hmmm. Looks like I forgot to strip formatting from the names. I forgot mods existed that modifies that....

As for the formatting to discord etc, we do have an open issue for that #5. It will be supported in a future version as soon as I get around to porting the required library. That would support formatting from both Discord -> MC and MC -> Discord

**Comment by hypherionmc** [comment]
Just giving an update here as well...

May or may not be messing with this

![image](https://user-images.githubusercontent.com/63595580/209688749-85bbd044-c88d-43b2-97f1-a6fc0061ce05.png)

**Comment by hypherionmc** [comment]
Formatting feature was release with 2.1
