### ISSUE TITLE
Not compatitable with simplechat

### ISSUE THREAD

**Issue by Blaze757** [hypherionmc/sdlink#29]
When I send a message from a game with simplechat installed, the message is not sent in the discord

**Comment by hypherionmc** [comment]
Yes that would make sense, since Simple Chat would essentially replace the systems that we rely on to relay messages. I'll have to look at adding compat for them

**Comment by hypherionmc** [comment]
Just took a quick look and see they actually have an API. So I'll add compat for them

**Comment by hypherionmc** [comment]
Okay so, it seems like there are some issues with both how Simple Chat works and how their API works. I have reported my findings to the developer, so once those are fixed, I'll revisit this request.

For reference, here is the [issue report](https://github.com/cayennemc/SimpleChat/issues/10)

**Comment by hypherionmc** [comment]
Okay, so as per the latest on Simple Chat, apparently the developer has abandoned the mod. So the only way to fix this now is if I do the fixes in Simple Chat myself and publish it

**Comment by hypherionmc** [comment]
Closing this for now, since the author of the mod in question abandoned it. If the mod is ever updated again, and the issue still persists in the upcoming V3 release, you are welcome to re-open
