### ISSUE TITLE
missing pack.mcmeta

### ISSUE THREAD

**Issue by arainflake** [hypherionmc/sdlink#30]
mod fails to load because of missing pack.mcmeta in the most recent forge 1.16.5 version

**Comment by hypherionmc** [comment]
Hmmmm, the missing pack.meta shouldn't cause the mod not to load. It will only cause resources from the mod to be missing from the game, which shouldn't be an issue as the mod doesn't contain any resources needed in-game.

Can you send me your full server log when this error occurred?

**Comment by hypherionmc** [comment]
Issue was fixed in Version 2.1
