### ISSUE TITLE
Death messages not relaying correctly

### ISSUE THREAD

**Issue by ghost** [hypherionmc/sdlink#32]
After our daily server restart today the bot has stopped relaying death messages correctly, instead only displaying them as `death.attack.player`, `player was cut into a block.minecraft.stonecutter` or`death.attack.sonic_boom`
Other messages are still relayed correctly, such as joining and leaving.
I added the server modlist in case there's any known incompatibilities I might've missed.

[modlist.txt](https://github.com/hypherionmc/sdlink/files/10202704/modlist.txt)

**Comment by hypherionmc** [comment]
Hi. Sorry for the late reply. 

I don't recognize any of the mods as a potential issue, atleast none that were reported.

Only thing I can think of is that the messages didn't load correctly with the server restart, as the way the bot relays the messages are just by hooking into the event that sends the message to the console, so if they display correctly in your chat/server console, there should be no reason for it not to work.

**Comment by ghost** [comment]
No worries!
I just checked the console and things aren't being displayed correctly either but instead as `death.attack.drown`, `chat.type.text` and the like. However, in-game everything is working fine and the chat messages are relayed to discord like usual as well. I tried googling around a little, however didn't really find anything on this exact issue. Do you have an idea? Or somewhere I could try looking for a solution instead, as it doesn't seem to be SDLink specifically causing this?
Thanks btw dude!

**Comment by hypherionmc** [comment]
Hey there. With the upcoming 2.1 release, some changes have been made in how advancements etc are being relayed.

If you still have this issue, you're welcome to test with one of the [Beta Builds](https://ci.firstdarkdev.xyz/job/Simple%20Discord%20Link/job/Forge-Fabric-Quilt/)

**Comment by hypherionmc** [comment]
Hopefully this issue is resolved with Version 2.1. If not, please feel free to re-open this issue
