### ISSUE TITLE
I might be trippin, but Idk how to enable the bot

### ISSUE THREAD

**Issue by milodthefartking** [hypherionmc/sdlink#33]
I changed configs and everything making sure everything was correct but the bot won't show up online, I am new to this so I don't know how it works and how to make sure the bot's code is run so that it shows up online and works. Any help, everyone else has their bot working so I think its just me

**Comment by hypherionmc** [comment]
Hi.

Do any errors show up in your log? If you're not sure how to check for them, please send your server log here.

**Comment by hypherionmc** [comment]
Closing this for now as no further feedback was received
