### ISSUE TITLE
Server won't launch when used with Aternos [1.19]

### ISSUE THREAD

**Issue by J3anPC37** [hypherionmc/sdlink#34]
Okay so I have a problem with using this mod in my (Aternos hosted) server where when I start the server, it stays at starting until it runs out of time because no one has and can join. I have tried deleting the mod and redownloading it (on the server), I have tried other mods but was unsuccessful, but somehow the Discord to In-game chat still works since I can see my discord messages through the console.

The version of my server is 1.19 for Forge and the version of the mod that I'm currently using is 1.19-1.3.0 (I have tried the latest version for 1.19 but I have encountered the same problem, I hope having an older version would solve the problem but that doesn't seem to be the case)

**Comment by hypherionmc** [comment]
This seems to be a common issue with Aternos. Not sure why it happens, but it happens. I still have to look into it and maybe get in touch with their support to figure this out.

**Comment by hypherionmc** [comment]
The mod seems to be working fine lately on Aternos. If this issue does still occur with the latest releases, feel free to re-open
