### ISSUE TITLE
Mod does not respect server nicknames

### ISSUE THREAD

**Issue by Canada-LaVearn** [hypherionmc/sdlink#37]
As the title says, the mod doesn't use the server nickname, it uses the users real username when sending messages. This makes it difficult to identify people that don't use their Discord name as their Minecraft username

**Comment by hypherionmc** [comment]
Do you mean from the discord side or the MC side?

**Comment by Canada-LaVearn** [comment]
Sorry, I meant Discord server nicknames. When a user sends a message in the Discord channel with a nickname, the name doesn't carry over to the Minecraft side, and instead shows their Discord username

**Comment by hypherionmc** [comment]
Fixed in v2.2.0
