### ISSUE TITLE
Interaction button menus

### ISSUE THREAD

**Issue by GiantessElsie** [hypherionmc/sdlink#39]
If u can could u maybe add interaction button menu for the mod for easier stuff like the status command then u don't need to press /status everytime then u can just press a interaction button and it refreshes 
![disabledbuttons](https://user-images.githubusercontent.com/99464192/217272347-e3d3e184-17aa-436c-9f86-aeb92ed9d748.png)

**Comment by hypherionmc** [comment]
Implemented in v2.2.0
