### ISSUE TITLE
Incompatible with Beautified-chat-server

### ISSUE THREAD

**Issue by BUBUSTEIN13** [hypherionmc/sdlink#43]
This mod works 85% with beautified chat. If a player sends a message in-game, the bot doesn't send it on discord chat.

**Comment by hypherionmc** [comment]
So looks like they use their own system for sending messages, but it does appear like they have an API, so I'll see what I can do from my side to add compact

**Comment by hypherionmc** [comment]
Finally support since 3.1.0
