### ISSUE TITLE
Live Player count & Online Discord Count

### ISSUE THREAD

**Issue by GiantessElsie** [hypherionmc/sdlink#45]
Okay my idea is if it is possible is config the mod like u know https://serverstatsbot.com/ can u make the idea that u can see who is online on the discord server on the channel section and see who is online on the minecraft server no names just numbers and channel names and a category name customization aswell

**Comment by KuryKat** [comment]
Not sure if that would be a great addition, as the bot's status can already show such information about the Minecraft server, but we will discuss about it

**Comment by KuryKat** [comment]
About adding a way to show the discord's server status, like how many members are online, use other bot, simple as that, the mod is supposed to be about the Minecraft Server, and not really about the Discord Server.

**Comment by hypherionmc** [comment]
Like @KuryKat mentioned, this doesn't really fit the scope of the bot. The Minecraft player count possibly be implemented, but definitely not the discord side. The bot you linked already does a great job of this, and would only add unnecessary technical debt to the mod. For now, I will keep this in mind for V3, for the Player count only
