### ISSUE TITLE
[Feature] Client Side stuff

### ISSUE THREAD

**Issue by vaporvee** [hypherionmc/sdlink#5]
maybe add something that you can copy the link code with a button or that you can press a button to join the discord. 
Also some ingame chat formatting could be cool that it looks like in discord. For example discord formating like `this` or underlined italic or bold text and maybe emojis

**Comment by hypherionmc** [comment]
I have been considering adding a "generator" to make inviting the bot easier with the correct perms and stuff already selected.

As for the formatting, I honestly have no clue how to implement that in Minecraft, and it sounds like a nightmare to maintain. I will look into it, to see if there are any existing libraries that can be used or look at making a custom, basic one

**Comment by vaporvee** [comment]
i meant inviting for the user on the server where the bot is on not a bot invite link

**Comment by hypherionmc** [comment]
Oh yeah. There is already a command/config option to include an invite link. I should be able to make it click-able in game. I have done it before for another mod

**Comment by hypherionmc** [comment]
Alright, it's been a long while.... Life has been hectic, but SD Link 1.2 now includes clickable invite links. As for the markdown support, I found a library capable of doing that, but I first need to update/port it, and I don't currently have time for that, but, that is a feature that can be expected from a future release

**Comment by hypherionmc** [comment]
![image](https://user-images.githubusercontent.com/63595580/209688693-718fe15c-a520-43e3-8cdd-c6bf86998792.png)

**Comment by hypherionmc** [comment]
This feature was finally implemented with SDLink 2.1 which was released today
