### ISSUE TITLE
Discord command /whitelist list formatting

### ISSUE THREAD

**Issue by Hellhium** [hypherionmc/sdlink#50]
Underscores (`_` ) are not escaped in the command

**Comment by hypherionmc** [comment]
Any more details? Examples of what happens?

**Comment by Hellhium** [comment]
![image](https://user-images.githubusercontent.com/11504877/231106840-00005e7b-d278-407b-b65d-eee1ffadba80.png)
`muimuiiijr` is supposed to be `muimuiii_jr`
`Ar2ino` is `Ar2ino_` 
The solution would be just replacing `_` by `\_` if i remember correctly

**Comment by hypherionmc** [comment]
Okay, so if you use the whitelist command in game, `/whitelist list` in mc, does it show the same? Reason I'm asking is, the whitelist system on the bot is just bridged directly to the minecraft system, so it literally just relays what the game is showing.

**Comment by Hellhium** [comment]
![image](https://user-images.githubusercontent.com/11504877/231110182-af4d6881-7104-4250-b083-84277d204590.png)

In game the command works fine, discord just interprets text as markdown and puts everything between two underscores in italic
https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by hypherionmc** [comment]
Although I forgot to add this to the changelog, this issue was fixed with 2.2.2 which was released last night. If this is still a problem, please let me know so it can be fixed :)
