### ISSUE TITLE
MC/Discord Linking Nickname Format

### ISSUE THREAD

**Issue by Jh16** [hypherionmc/sdlink#51]
Hello, I'd like to request to have the bot change the nickname directly to the linked MC name instead of the current format.
Current format being:
discordname[MC:mcname]
to
mcname

Many users on my discord server already have their discord account name as their MC name. Plus it would make things so much cleaner to look at.

Thankies!

**Comment by hypherionmc** [comment]
Hi. Okay so, this feature was implemented based on a previous request, which requested to have the username in that format.

We would have to make it configurable, which shouldn't be an issue. This will only be implemented with V3 of the mod though, since we are busy rewriting the entire mod

**Comment by Jh16** [comment]
Awesome! Thanks for the quick response. Certainly look forward to it 🙂

**Comment by hypherionmc** [comment]
Implemented in V3 beta
