### ISSUE TITLE
Unwanted "tellraw" Output

### ISSUE THREAD

**Issue by Jh16** [hypherionmc/sdlink#52]
Hello again. I and the members of the server I'm a part of are still enjoying the mod and its functionality. However, after recently having to ban an x-rayer, the co-owners (myself and another) wish to utilize a datapack for keeping informed regarding such activity. So we wanted to give [TotallyRandom's Xray Prevention Data Pack](https://www.planetminecraft.com/data-pack/totallyrandom-s-xray-prevention-datapack-trx-1-19-3/) a try as it looks and functions well for our needs without hindering everyone else via a server-side mod to combat x-raying.

Unfortunately, it seems this mod outputs the info the datapack gives out, which is through the `tellraw` command to show for those with a specific tag.

I'm not sure how this could be corrected. I've attempted to utilize Discord's own AutoMod feature to block a specific phrase used in all of the messages but I haven't been able to get that to work properly. Maybe because it won't target bots specifically, which is kind of annoying since it doesn't have the specified permissions to be always excluded from the filter rules.

Would it be possible to have the option to disable output for tellraw? Or would that be too much work to implement? If not, that's fine as well. No harm in asking about it. :)

Thanks

**Comment by hypherionmc** [comment]
Hi there.

Yeah tellraw support is currently still experimental and still needs a lot of work.

For now, you can disable tellraw (which would disable all messages from tellraw), by changing `relayTellRaw` in the config to `false`

**Comment by Jh16** [comment]
Oh goodness, I must have been blind when I looked through the config file. xD

Thank you, that solves it!
