### ISSUE TITLE
Call for Alpha Testers on V3

### ISSUE THREAD

**Issue by hypherionmc** [hypherionmc/sdlink#55]
After months of work, the first Alpha builds (or testing builds) of Simple Discord Link V3 is nearing.

There is no official eta for the builds yet, and they won't be 100% feature complete at the time of the first builds.

The main focus is getting the existing features implemented, working and tested. From there, we will start building on the features reserved for the V3 release.

We need as many testers as possible, to make sure when the official release is made, it goes out with little to no bugs, and we can finally end the buggy v2 series.

If you are interested in helping with testing, please leave a comment below. If you are in our discord server, please grab the Test Monkey role from the role selection channel.

The first alpha builds can be expected in the next 2 weeks, maybe sooner if everything goes well.

**Comment by Whitebrim** [comment]
Hello, I'm using simple chat (fork) and have issues described in https://github.com/hypherionmc/sdlink/issues/29 (chat messages are handled as plugin outputs).
I'm looking forward to test v3.
