### ISSUE TITLE
Config to use commands from Discord chat

### ISSUE THREAD

**Issue by jamieroot** [hypherionmc/sdlink#56]
It's useful for when, for example, someone from discord chat wants to /w to someone but they can't join the mc server. If you still want to have some staff commands while still having commands that people can use, you can just configure what role can execute the commands.

**Comment by hypherionmc** [comment]
Sounds good. Tbf, I don't even remember why commands where limited to the console channel only. 

But definitely something we can change in the V3 version

**Comment by jamieroot** [comment]
how tf was that so fast. But still thanks for responding!

**Comment by hypherionmc** [comment]
I was literally looking at my phone the moment you created the issue and saw the push notification from discord lol

**Comment by jamieroot** [comment]
Damn, I got really lucky then xD

**Comment by hypherionmc** [comment]
Restriction was lifted in 2.2.3
