### ISSUE TITLE
link account - automatic whitelisting when it has a specific role

### ISSUE THREAD

**Issue by mal0andre** [hypherionmc/sdlink#59]
- [x] Allow people to link their account, but the administrator can choose if their name on discord will be changed with their minecraft name
- [ ] And enable automatic whitelisting when they have a specific role (they must have previously linked their mc account)

**Comment by hypherionmc** [comment]
1) Duplicate of #51 
2) Will be added to V3

**Comment by mal0andre** [comment]
Sorry for the duplicate,
but the possibility to disable renaming is not mentioned, am I wrong?

Thanks

**Comment by hypherionmc** [comment]
Yeah it's not mentioned, but the idea is:

CHANGE_NICKNAME, IGNORE_NICKNAME for options
and then "Nickname Format" which will allow you to specify how the nickname is formatted if you are using it

**Comment by hypherionmc** [comment]
While this has been implemented somewhat in the V3 alpha builds, it has proven problematic and unstable. #89 might be a proper way to implement both these.

Feel free to share your thoughts there

**Comment by hypherionmc** [comment]
Implemented in V3 beta
