### ISSUE TITLE
[BUG] Typing a message with quotes causes the bot to ignore it

### ISSUE THREAD

**Issue by MoriyaShiine** [hypherionmc/sdlink#6]
**Describe the bug**
Whenever someone says something in game that begins and ends with ", the message does not display in discord.

**To Reproduce**
1. Set up the bot
2. Join the server in Minecraft
3. Type anything, for example say "test" **with** quotes
4. The message does not get sent to discord

**Expected behavior**
Messages with quotes should appear in the bot

**Screenshots**
message log: 
![Screenshot_2022-02-16_18-38-20](https://user-images.githubusercontent.com/45156123/154381981-cac7090b-f2ec-4fa9-903c-c1821b83f46d.png)
in discord: 
![Screenshot_2022-02-16_18-38-55](https://user-images.githubusercontent.com/45156123/154381990-544ae14c-ae82-4b9a-a56f-43ae3359bfb2.png)

**Versions (Please give exact numbers, not LATEST!):**
 - Mod Version: 1.18.x-1.1
 - Mod Loader (Put an x inbetween [])
   - [] Forge
   - [x] Fabric
   - [] Spigot etc
 - Mod Loader Version: 0.13.1
 - Minecraft Version: 1.18.1

**Additional context or crash logs**

**Comment by hypherionmc** [comment]
Thanks for reporting, and sorry for me taking so long to respond. Life has been hectic.... SD Link 1.2 fixes this issue :)
