### ISSUE TITLE
modrinth description

### ISSUE THREAD

**Issue by vertex101** [hypherionmc/sdlink#62]
i went through Modrinth to use ur mod and noticed that by the permissions listed on Modrinth the mod can only be downloaded from curseforge so dont know if u wanna update that on Modrinth

**Comment by hypherionmc** [comment]
Updated it. The modrinth moderators actually pointed it out when I created the project, but I just completely forgot about it.

Thanks for reminding me

**Comment by vertex101** [comment]
np was just looking out
