### ISSUE TITLE
[Feature Request]: Custom Message Type

### ISSUE THREAD

**Issue by BONNe** [hypherionmc/sdlink#65]
Currently, in Simple Discord Link, there is these Server Chat Message Types that are available to display:
   - CHAT,
   - START_STOP,
   - JOIN_LEAVE,
   - ADVANCEMENT,
   - DEATH,
   - COMMAND,
   - CONSOLE
   
I would like to display my own custom message to Discord chat, that does not match any of these types. I would like to have the ability to send a message that is similar to the JOIN_LEAVE or DEATH where a message is sent by a bot without the author who send the message.

The name could be CUSTOM, and the text would not require any parsing options, maybe just style (italic).

**Comment by hypherionmc** [comment]
Hi.

I guess this is either relating to my request [#3](https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/issues/3) or from a convo with Masuary.

I will add in the message type for you.

If you need any help with using the code, I will gladly assist you. I will have this added by the latest tomorrow afternoon

**Comment by hypherionmc** [comment]
Implemented in v2.2.3
