### ISSUE TITLE
Vanish Integrations

### ISSUE THREAD

**Issue by joeyak** [hypherionmc/sdlink#66]
Would it be possible to add vanish integration? I would look into it now but buried under other development that's needed. There's a VanishAPI that can be used to check if a player is vanished and VanishEvents that fire when the vanish status changes. https://github.com/DrexHD/Vanish#developers

**Comment by hypherionmc** [comment]
Sure thing, this will only be implemented in V3 though, which is now in early alpha testing

**Comment by hypherionmc** [comment]
Implemented in V3 beta
