### ISSUE TITLE
[1.20.1-Forge] Crash when loading server.

### ISSUE THREAD

**Issue by Gbergz** [hypherionmc/sdlink#67]
Title^

Seems its conflicting with mods.

Simple Discord Link Bot: 2.2.2 | https://legacy.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot/files/4578593 
CraterLib: 1.0.1 | https://legacy.curseforge.com/minecraft/mc-mods/craterlib/files/4609413

Logs: https://gist.github.com/Gbergz/2ab0bb39f76d92bdac3f80126f690f47

**-** Gbergz

**Comment by NighthowlerStudios** [comment]
This log gives absolutely no crash trace.  Please find the crash log.

**Comment by Gbergz** [comment]
![bild](https://github.com/hypherionmc/sdlink/assets/26634554/81bcf8cf-f184-4a32-85e7-da37d1aed2f5)

**Comment by Gbergz** [comment]
There is no crash log file generated.

**Comment by NighthowlerStudios** [comment]
what you just sent is the crash trace needed anyway

**Comment by Gbergz** [comment]
Gotcha, here's the text in raw form copied from console window.
https://gist.githubusercontent.com/Gbergz/20af525b58a2070068ed9868936d9f1e/raw/075286102dd5a144b5d16483a8be0bd411210e76/gistfile1.txt

**Comment by NighthowlerStudios** [comment]
as you can see, the conflict is rftools, which shares the same library as simplerpc.  due to a recent change in most modloaders, two mods cannot share libraries.  one or the other will need to eliminate this dependency or agree to share a core mod.

(specifically the library fasterxml)

**Comment by Gbergz** [comment]
It gives a different mod as the cause each time I boot.
![bild](https://github.com/hypherionmc/sdlink/assets/26634554/1f99683e-3168-45a2-852f-62967048c550)
![bild](https://github.com/hypherionmc/sdlink/assets/26634554/92a66484-7b1e-4eb5-af55-16fe60488956)
![bild](https://github.com/hypherionmc/sdlink/assets/26634554/576897ec-3a21-42ae-b0e4-97f5f34260d6)

**Comment by NighthowlerStudios** [comment]
it's telling you a different wording because of thread race.  each mod can load whenever the hell they want and not in a specific order.  the error here is the same.  fasterxml is present in both mods, causing a crash

**Comment by NighthowlerStudios** [comment]
it's possible what you've actually found is a modloader bug, and you may wish to report that to the modloader's devs.  I'm not convinced this many mods share the same library

**Comment by NighthowlerStudios** [comment]
make sure your modloader is up to date or using its stable branch

**Comment by Gbergz** [comment]
Interesting, hm. 

Yeah I am on the latest recommended forge build. 47.1.0

**Comment by hypherionmc** [comment]
This is a know issue with any mod that uses JACKSON. I have to go compare our new V3 alpha builds to V2 to figure out whats different, since V3 doesn't have this issue.

Also, you're the second one in two days using GModloader. What is up with that? Never even heard of it till yesterday

**Comment by Gbergz** [comment]
Gotcha.

Groovy Modloader is a library addon: https://legacy.curseforge.com/minecraft/mc-mods/gml

It's in the modpack because of this mod: https://legacy.curseforge.com/minecraft/mc-mods/eating-animation-forge
It has it as a dependancy.

**Comment by hypherionmc** [comment]
I see. Was just wondering lol.

But yeah, in this case, the conflict is with Groovy Modloader. That was discovered yesterday, so forge is not really doing a good job of identifying the correct conflicts

**Comment by Gbergz** [comment]
So, I forgot Eating Animations is a client mod, So is the Groovy Modloader mod too apparently. 
So I can remove it server side, and now it boots fine.

**Comment by hypherionmc** [comment]
This issue should now be fixed with 2.2.3. I tested this myself and the server booted up without crashing
