### ISSUE TITLE
[Feature] Custom colors and avatars images for embeds

### ISSUE THREAD

**Issue by LempekPL** [hypherionmc/sdlink#69]
![image](https://github.com/hypherionmc/sdlink/assets/37885098/e31cc936-7dde-4e8b-be24-f2aea2a7b352)
Additional `color = ""` which will take #hex as input and `embedAvatarType = "HEAD"` same as `playerAvatarType`
To be able to use image and text on the same line you would need to use author attributes (author, author icon url)
Also author name has limit of 256 characters and forced bold text.

**Comment by hypherionmc** [comment]
Fully customizable embeds are partially implemented in V3. Keeping this open so I can remember to finish it

**Comment by hypherionmc** [comment]
Implemented in V3 beta
