### ISSUE TITLE
Small enhancements

### ISSUE THREAD

**Issue by PolyframeX** [hypherionmc/sdlink#70]
For the mod, when an attachment is posted, it will completely ignore this and send either a blank image or act like it didn't send at all. There should be a feature to where it at least shows that a attachment was sent, such as this:

`<PolyframeX> Hello World! (1+ Attachment)`

Obviously its just a mockup, but you get the idea. Same thing goes with emojis, but instead it would translate back to :sobbing:

**Comment by hypherionmc** [comment]
Implemented in V3 beta
