### ISSUE TITLE
[Feature Request] Admins can Whitelist/Link another User/Player

### ISSUE THREAD

**Issue by t0g3pii** [hypherionmc/sdlink#72]
When LinkedWhitelist and OnlyAdminWhitelist is enabled i would love to have a command as an admin that looks smth like this:
/whitelist add @discordUsername mcUsername

When that Command is performed, the mentioned Discord User should get the Verified and Whitelist Role and should be whitelisted on the Server.

Reason for that is that we want to control the Whitelist BEFORE a User joins. So they need to "apply" to get whitelisted. 
We could currently do that by restrictring the whitelist command to a specific role in the discord application settings but that destroys the "automation" process in my opinion.

**Comment by hypherionmc** [comment]
Thanks for opening. Otherwise I would've forgotten about this.

Just a question. Is it fine that the user still needs to pass the account verification process, (meaning join the server once, and perform a final command to confirm the MC account belongs to them), or do you want the admin whitelist to just complete it all in one, without any verification?

**Comment by t0g3pii** [comment]
> Thanks for opening. Otherwise I would've forgotten about this.
> 
> Just a question. Is it fine that the user still needs to pass the account verification process, (meaning join the server once, and perform a final command to confirm the MC account belongs to them), or do you want the admin whitelist to just complete it all in one, without any verification?

Maybe just an add option for that one? something like UserNeedVerify or something^ I personally would love to skip the verify part for them, but can understand ur point in wanting to have it in^^

**Comment by hypherionmc** [comment]
Implemented in V3 beta
