### ISSUE TITLE
[Feature] Commands and chat relay should show linked discord names for minecraft messages

### ISSUE THREAD

**Issue by Daenyth** [hypherionmc/sdlink#73]
When a chat message is relayed from the minecraft server into discord, it would be nice if it included the discord name when the minecraft account is linked.

Similarly, `/list` should use the name too

**Comment by hypherionmc** [comment]
I've actually been thinking about this for a couple of days. 

My idea was to use the Discord name for chat in discord, and the minecraft name for chats from discord.

If the user does not have an account linked, it will use the default behavior of taking the MC/Discord name.

Having commands executed as the player might be a little tough, but shouldn't be impossible

**Comment by hypherionmc** [comment]
Implemented in V3 beta
