### ISSUE TITLE
[Feature] Automatically un-whitelist MC accounts when Discord account is gone from server

### ISSUE THREAD

**Issue by Daenyth** [hypherionmc/sdlink#74]
I'd like to keep my whitelist controlled very tightly, and I noticed looking at `/linkedacc` that one of the accounts was linked to a discord account that had left my discord server.
I'd like the bot to automatically un-whitelist accounts that aren't still on the server

**Comment by hypherionmc** [comment]
Thanks. Otherwise I will forget about this when it gets lost in the chat

**Comment by j00w33** [comment]
Could this also be tied to a discord role? We have a patreon exclusive whitelist and if someone leaves the patreon role, then it would be nice to have this feature for that as well

**Comment by hypherionmc** [comment]
That was actually implemented with this request. Auto-whitelist/un-whitelist by role or roles

**Comment by hypherionmc** [comment]
Implemented in V3 beta
