### ISSUE TITLE
[Feature Request] Support for running commands on multiple bots at once

### ISSUE THREAD

**Issue by j00w33** [hypherionmc/sdlink#79]
Currently I have 2 MC servers. It works well enough, but the `/` commands need to be done per server. I can limit the commands to be used in certain chats, but it's still a manual process for all players to link themselves to each server

I would want something that would allow me to have a global "whitelist" channel where a user can run `/whitelist add username` and it pushes the command to all bots at once.  
I did some preliminary research and it's possible for a bot to listen for a particular message from another bot and trigger a command accordingly using webhooks.  
[Quora source](https://www.quora.com/How-can-I-use-a-bot-to-trigger-another-bot-in-Discord-Are-there-any-alternatives-to-do-this)  
A few questions were from 2 years ago so things have likely changed.

Alternatively, allow for 3rd party access to the webhooks. I'd be down to write my own bot to act as the middle man between the multiple bots.

**Comment by hypherionmc** [comment]
Implemented in V3 beta
