### ISSUE TITLE
[Bug] Channel Topic not Updating

### ISSUE THREAD

**Issue by AllOutJay** [hypherionmc/sdlink#8]
Minecraft version:
Minecraft 1.19

Mod Version:
[Fabric/Quilt 1.19.x] Simple Discord Link - 1.3.0

Description of the issue:
The bot does not appear to update the channel topic despite the configuration having it filled out or having Discord permissions. I have gone ahead and attached a censored text version of the config since Github doesn't allow toml, and I have attached a screenshot of the bot having permissions. Also to mention, the bot's presence does update with the same message that was intended for the channel topic.

[simple-discord-bot.txt](https://github.com/hypherionmc/sdlink/files/8936421/simple-discord-bot.txt)
[Discord permissions](https://user-images.githubusercontent.com/80604256/174500921-7cae6854-4380-446b-a777-d56efc0548d7.png)

**Comment by hypherionmc** [comment]
Hi there. The config looks correct. Please note that topic updates only occur once every 10 minutes. This is a discord ratelimit sadly

**Comment by AllOutJay** [comment]
Looks you are right, I just had to wait about 10-11 minutes for it to update. I guess I am use to the other mods updating sooner and then updating depending on the rate limit. 

I also thought the Channel Topic updates can happen twice every 10 minutes?

**Comment by hypherionmc** [comment]
I'll look into the rate limits again. When I first added that feature it was updating every 5 minutes, and then got struck with a ratelimit

**Comment by hypherionmc** [comment]
Working through these reports as I'm doing bug fixes and updates.

I have confirmed that Topic update rate limits are indeed 2 per 10 minutes, so I will adjust the mod accordingly. 

To stay within rate limits, I'll adjust it down from 11 minutes to 6 minutes.
