### ISSUE TITLE
[Feature Request] Use discord nickname in Discord -> MC chat

### ISSUE THREAD

**Issue by PingIsFun** [hypherionmc/sdlink#84]
Use discord nickname in Discord -> MC chat.
Currently there is only one parameter `%user%` which is replaced by the discord name.
I'd like there to also be a `%nickname%` field which is replaced by the member's nickname in the guild.

After looking at the code i found out that [the "problem" is in this line in sdlink-lib](https://github.com/hypherionmc/sdlink-lib/blob/7d9dded7909031dbd1645419220f156b429e4083/src/main/java/me/hypherionmc/sdlinklib/discord/DiscordEventHandler.java#L75)
```java
minecraftHelper.discordMessageEvent(event.getMember().getEffectiveName(), event.getMessage().getContentRaw());
```
the current implementation [just passes the user name as a string](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/Member.html#getEffectiveName())
you can get the nickname with [getNickname()](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/Member.html#getNickname())

i see 2 possible solutions either just pass in `Member`  and process it later or add a `nickname` argument to `discordMessageEvent`

and in [sdlink repository here just need's to be added a way to replace the %nickname% with the nickname](https://github.com/hypherionmc/sdlink/blob/ef9a7bcce02fe04ca67713a897659c949714599b/Common/src/main/java/me/hypherionmc/sdlink/server/ServerEvents.java#L307)
```java
MutableComponent component = modConfig.messageConfig.formatting ? MinecraftSerializer.INSTANCE.serialize(modConfig.chatConfig.mcPrefix.replace("%user%", s) + s1) : Component.literal(modConfig.chatConfig.mcPrefix.replace("%user%", s) + s1);```

**Comment by hypherionmc** [comment]
Just to relay here what I said on discord.

`getEffectiveName()` tries to first use the member nickname, then if that's not found, it uses the username.

Discord now has 3 types of names. Server nicknames, Global name, and username.

The bot library we use does not yet support the second one (global). So if you don't have a server nickname set, it will use your username

**Comment by hypherionmc** [comment]
Just to show that this does work, here is a chat relayed from my discord (where my nickname is set to H).

`[15:01:59] [pool-3-thread-2/INFO] [minecraft/MinecraftServer]: [Discord] H: Chat test`
