### ISSUE TITLE
RFC (Request For Comment) - Replacing the Whitelisting And Linking system with a unified system

### ISSUE THREAD

**Issue by hypherionmc** [hypherionmc/sdlink#89]
So this is an idea that came up, while discussing the issues surrounding the current whitelist and account linking system.

An idea has been pitched to nuke both these systems, and replace it with a new, much simpler verification system.

So, you will have the following config options:

`requireVerification = true`
`verificationMessage = "Hello, please visit the #confirm channel in our discord and run command /confirm {code} to get access to the server`
`requiredRoles = []` or `requiredRoles = ["1323445655346346"}`

So if option one is enabled, and user tries to join your server, they will be kicked with `verificationMessage`. `{code}` will be replaced with the actual code they need to use.

Once they did that, they can access the server, unless, you also have `requiredRoles` configured. If you do, they will also need one of the roles specified there to join the server. This will allow things like patreon only servers, to have automated access control based on the players patreon status.

This will also remove the complicated process of whitelisting and linking your account, since it will be an all in one system. 

Automated role assignments when the user verified their account will still be possible, to allow server owners to do things like giving a special role to verified players, or, gatekeeping their server chat channel behind a certain role, until the player is verified

This will be a simpler setup process for server admins, and a more pleasant experience for the player, without having to go through tons of hurdles to get themselves whitelisted.

React with either 👍 or 👎 and feel free to share your thoughts or concerns below.

**Comment by GeneralZyonix** [comment]
Great idea! Much easier for me (server owner) and my (future) players

**Comment by j00w33** [comment]
This sounds great. Removes a ton of complexity especially my removing the combination of MC whitelist, AND discord role list.  
Got my support :)

**Comment by KuryKat** [comment]
I believe this is a good change, it would make the life of all users, and developers, easier, and clean up code that should've been done differently.

**Comment by hypherionmc** [comment]
Implemented in V3 beta
