### ISSUE TITLE
My Minecraft Server Isnt Running

### ISSUE THREAD

**Issue by Doglover2185** [hypherionmc/sdlink#90]
My Minecraft Server Runs On Forge 1.19.2 And I linked everything up and yet it doesn't seem to want to run every time I start the server please help!! Heres The Log, It Didnt Make A Crash Report For Some Reason But it did crash
[latest.log](https://github.com/hypherionmc/sdlink/files/13057795/latest.log)

**Comment by hypherionmc** [comment]
You mis-spelled `true` somewhere in the config. You have it as `ture`

**Comment by Doglover2185** [comment]
Thank You Lol I Fell Stupid
