### ISSUE TITLE
[BUG] Replying to webhook messages shows nothing in game

### ISSUE THREAD

**Issue by j00w33** [hypherionmc/sdlink#93]
Versions:
Latest Forge and Fabric.

What happens:
I reply to a webhook message in discord and no message appears in game.

Expected behavior:
I reply to a webhook message in discord and that message appears in game.

Appears to be related to the webhook message not having a proper author, so the reply message breaks

**Comment by hypherionmc** [comment]
Fixed in 3.0.1 Beta
