### ISSUE TITLE
Bot Not Going Online

### ISSUE THREAD

**Issue by AALUND13** [hypherionmc/sdlink#99]
I'm currently facing challenges with getting my bot online and logging activities. The server is hosted by Hostinger, and I've ensured that the token and Channel ID are correctly configured. Despite these settings, the bot refuses to go online, and the logging module remains inactive.

For your convenience, I've attached a [link](https://github.com/hypherionmc/sdlink/files/13926454/simple-discord-link.txt) to the simple-discord-link.txt file, which contains relevant information.

If you have insights or suggestions on why this issue might be occurring, I would greatly appreciate your assistance.

Thank you.

**Comment by AALUND13** [comment]
I think it is logging 
Cause one log said this
![Screenshot 2024-01-12 221928](https://github.com/hypherionmc/sdlink/assets/58748165/7437c543-7da4-4dbb-bd66-f16153ffe357)

**Comment by hypherionmc** [comment]
Is there any possibility that you can provide your latest.log from the server please?

**Comment by AALUND13** [comment]
There is the server log
[latest.log](https://github.com/hypherionmc/sdlink/files/13927562/latest.log)

**Comment by hypherionmc** [comment]
Shoot, sorry I thought I responded to this.

Which version of the mod are you on? It does seem like the mod is loading, but not doing anything else after that. So I wonder if this is an issue with CraterLib, or SDLink

**Comment by AALUND13** [comment]
I not turn on any Privileged Gateway Intents let me turn then on see that fix it

**Comment by AALUND13** [comment]
I turn those on bots sill offline

**Comment by AALUND13** [comment]
> Shoot, sorry I thought I responded to this.
> 
> Which version of the mod are you on? It does seem like the mod is loading, but not doing anything else after that. So I wonder if this is an issue with CraterLib, or SDLink

Everything is up to date

**Comment by AALUND13** [comment]
Oh never mind I also so have wrong version of the mod using the old config so I updated thew mod to 3.0.1 the mod seen be working now.
